version: "3"
services: 
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: TestProject
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root@123
      DATABASE_PORT: 5432
      DATABASE_HOST_NAME: db
      DATABASE_NAME: TestProject
      ALGORITHM : HS256
      SECRET: supersecret
      EXPIRATION_TIME: 30

volumes:
  db-data:





       